server:
  port: 8888
spring:
  security:
    user:
      name: root
      password: s3cr3t
  cloud:
    config:
      server:
        native:
          # search-locations: file://${user.home}/Developer/vocset-api/src/main/resources
          search-locations: file:///app/config-server
  application:
    name: config-server
